pre-commit:
  parallel: true
  commands:
    # pokemon-art:
    #   run: .scripts/hooks/pre-commit-pokemon.sh
    #   stage_fixed: false
    vale:
      glob: "**/*.md"
      run: vale --config .vale.ini {staged_files}
    shellcheck:
      run: .scripts/hooks/pre-commit-shellcheck.sh {staged_files}
    stylua:
      glob: "**/*.lua"
      run: .scripts/hooks/pre-commit-stylua.sh {staged_files}
      stage_fixed: true
    luacheck:
      glob: "**/*.lua"
      run: .scripts/hooks/pre-commit-luacheck.sh {staged_files}
    yaml-validation:
      glob: "**/*.{yml,yaml}"
      run: .scripts/hooks/pre-commit-yamllint.sh {staged_files}
    gitleaks:
      run: gitleaks protect --staged --no-banner --log-level=error --baseline-path=.gitleaks-baseline.json
    sort-spell:
      glob: "dot_config/nvim/spell/.en.utf-8.add"
      run: .scripts/hooks/pre-commit-sort-spell.sh {staged_files}
      stage_fixed: true

pre-push:
  commands:
    gitleaks:
      run: gitleaks detect --no-banner --log-level=error --baseline-path=.gitleaks-baseline.json

# Reduce output verbosity
output:
  - success
  - failure
  - summary
skip_output:
  - meta
