---
default: true
MD013: false  # Line length
MD033: false  # No inline HTML
MD041: false  # First line in file should be a top level heading
MD045: false  # Images should have alternate text
line-length: false
no-inline-html: false
MD024:
  siblings_only: true
MD026:
  punctuation: ".,;:!"
MD029:
  style: ordered
MD036: false
MD025: false
