gui:
  # Use the mocha catppuccin theme with blue accent
  theme:
    activeBorderColor:
      - '#89b4fa' # blue
      - bold
    inactiveBorderColor:
      - '#a6adc8' # subtext0
    optionsTextColor:
      - '#89b4fa' # blue
    selectedLineBgColor:
      - '#313244' # surface0
    cherryPickedCommitBgColor:
      - '#45475a' # surface1
    cherryPickedCommitFgColor:
      - '#89b4fa' # blue
    unstagedChangesColor:
      - '#f38ba8' # red
    defaultFgColor:
      - '#cdd6f4' # text
    searchingActiveBorderColor:
      - '#f9e2af' # yellow
