## AUTOMATIC RENAMING
setw -g allow-rename on
set -g automatic-rename on
set-option -g automatic-rename-format "#{b:pane_path}"
set-option -g renumber-windows on

## TMUX STATUS BAR ON TOP
set-option -g status on
set -g status-position top
setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-border-lines single

