##
## TMUX KEYBINDINGS CONFIGURATION
##

##
## LIST WINDOWS and SESSIONS
##
bind S choose-session
bind '"' choose-window
bind ^A last-window
bind ^W list-windows
bind w list-windows

##
## VERTICAL SPLITS
##
bind v split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

##
## HORIZONTAL SPLITS
##
bind - split-window -c "#{pane_current_path}"
bind s split-window -c "#{pane_current_path}"

##
## NEW WINDOW
##
bind c new-window -c  ~/

bind-key -n C-S-p swap-window -t -1\; select-window -t -1
bind-key -n C-S-n swap-window -t +1\; select-window -t +1

##
## PANE NAVIGATION
##
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind X kill-pane
bind x swap-pane -D

##
## RESIZE PANE
##
## USE MOUSE TO RESIZE PANE (much easier)
##
bind z resize-pane -Z
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7 

## VIMLIKE COPY MODE AND SELECTION
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

##
## OTHER KEY BINDINGS
## 
bind R command-prompt "rename-window %%"
bind ^L refresh-client
bind ^X lock-server
bind ^D detach
bind * list-clients
bind : command-prompt
bind * setw synchronize-panes
bind-key -n C-S-k send-keys "clear"\; send-keys "Enter"
unbind t
bind-key t set-option status

