##
## TMUX CONFIGURATION 
## 
## symlinked to: ~/.tmux.conf
##

##
## MAKES CONFIGURATION PORTABLE BETWEEN MACHINES OF DIFFERENT OS
##
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin:$PATH"
set -g default-command "$SHELL"

## 
## NON-NEGOTIABLE CONFIGURATIONS
##
set -g history-limit "100000"
set -g escape-time "0"
set -g set-clipboard "on"
set -g mouse "on"

## 
## KEYBINDINGS
##
## CHANGE TMUX PREFIX TO C-a (Control + a)
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

## RELOAD CONFIG WITH C-a r (Control + a followed by r)
unbind r
bind r source-file ~/.config/tmux/tmux.conf 

##
## KEYBINDINGS
##
source-file ~/.config/tmux/tmux.keybindings.conf

##
## PLUGINS
##
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'b'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'tmux-plugins/tmux-open'
# set -g @plugin 'olimorris/tmux-pomodoro-plus'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'

##
## THEME
##

## TMUX COLOR CONFIGURATIONS
set -g default-terminal "tmux-256color"
set-option -g terminal-overrides ',xterm-256color*:RGB'
set -as terminal-features ',xterm*:RGB'

## TMUX STATUS BAR
source-file ~/.config/tmux/tmux.status.conf

##
##  CATPPUCCIN THEMES
##
set -g @plugin 'catppuccin/tmux'
source-file "~/.config/tmux/tmux.theme.catppuccin.conf"
run '~/.config/tmux/plugins/tpm/tpm'

## REFRESH STATUS LINE EVERY 1 SECOND
set -g status-interval 1
