---
name: Lint

on:
  pull_request:
    branches: ["**"]

jobs:
  GO:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          working-directory: _tests_
          args: --max-issues-per-linter=0 --max-same-issues=0
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAML formatting
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml

  SHELL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.chezmoiscripts'

  MARKDOWN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '**/*.md'
          version: 2.30.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
